name = "quiz-app"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[vars]
NEXT_PUBLIC_FIREBASE_API_KEY = "AIzaSyBlDhGfleNUOfSDXNreUn9cDH-lAW0KjTM"
NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN = "quiz-app-4117b.firebaseapp.com"
NEXT_PUBLIC_FIREBASE_PROJECT_ID = "quiz-app-4117b"
NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET = "quiz-app-4117b.firebasestorage.app"
NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID = "1023575960460"
NEXT_PUBLIC_FIREBASE_APP_ID = "1:1023575960460:web:72a931bf304acffe28c4a9"
